### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by flexdinesh** [flexdinesh/blogster#3]
List of things in pipeline for Blogster. I'll smash through them as and when I find time.

**All themes:**

- [ ] Markdoc custom component - Image with caption
- [ ] theme-color meta - set in ThemeScript.astro and update during theme toggle
- [ ] DarkMode.astro - convert to web component
- [ ] GitHubGist.astro - convert to web component
- [ ] Nav.astro - copy from Bubble to all themes and convert to web component
- [ ] blog/projects page - align items baseline b/w title and date
- [ ] fontawesome - add RSS icon to bareminimum and header
- [ ] Add code comment for favicon on how it's generated
- [ ] Add code comment for Tailwind css variables and how they work
- [ ] FIX: OG image URL for blog posts
- [ ] Frontmatter schema - refactor reused types

**Bubblegum:**

- [ ] Remove heading `before` border for h3 and higher

**Sleek:**
- [ ] Remove 50-900 shades and replace with one or two. It's an overkill.

**Newspaper:**
- [ ] Remove 50-900 shades and replace with one or two. It's an overkill.
